# Generated by Django 4.1.5 on 2023-03-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_reservation_user_rent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
