# Generated by Django 4.1.5 on 2023-03-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('a', 'Automatic'), ('m', 'Manuel')], max_length=1),
        ),
    ]
