# Generated by Django 4.1.5 on 2023-04-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_gear'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='user_rent_date',
        ),
    ]
